platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfseceng/credhub

inputs:
- name: credhub-api-site

outputs: 
- name: built-site

run:
  path: ./credhub-api-site/ci/build.sh
